-- apps/worker/sql/0004_add_limit_type.sql
-- Add limit_type wire envelope column.
-- Purpose: persist the per-invocation `limit_type` flag (5h | weekly)
-- alongside each event so cron can split each cohort
-- ((tier, harness, region)) into per-limit-type cells.
-- Stored alongside other dimension columns; serde-side closed-enum
-- validation in apps/worker/src/event.rs (LimitType from crates/event-schema).
--
-- Apply manually per branch:
--   psql "$PLANETSCALE_STAGING_URL" < apps/worker/sql/0004_add_limit_type.sql
--   psql "$PLANETSCALE_MAIN_URL"    < apps/worker/sql/0004_add_limit_type.sql
--
-- NOT NULL safe for initial v1 rollout. Clear staging smoke-test rows before
-- applying with `TRUNCATE TABLE events`; fixtures regenerate. Production has
-- no rows. If rows DO exist on a future branch, use the safe-migration pattern:
-- ADD ... NULL, backfill, ALTER ... SET NOT NULL.
--
-- Allowed values are enforced application-side by crates/event-schema's
-- LimitType closed enum. DB-side this starts as plain TEXT; 0005 adds the
-- CHECK constraint after the column exists on both branches.

ALTER TABLE events ADD COLUMN limit_type TEXT NOT NULL;
