/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankRouteImport } from './routes/rank'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as InstallRouteImport } from './routes/install'
import { Route as DataRouteImport } from './routes/data'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MethodologyChangelogRouteImport } from './routes/methodology.changelog'

const RankRoute = RankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyChangelogRoute = MethodologyChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => MethodologyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/install': typeof InstallRoute
  '/methodology': typeof MethodologyRouteWithChildren
  '/rank': typeof RankRoute
  '/methodology/changelog': typeof MethodologyChangelogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/install': typeof InstallRoute
  '/methodology': typeof MethodologyRouteWithChildren
  '/rank': typeof RankRoute
  '/methodology/changelog': typeof MethodologyChangelogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/install': typeof InstallRoute
  '/methodology': typeof MethodologyRouteWithChildren
  '/rank': typeof RankRoute
  '/methodology/changelog': typeof MethodologyChangelogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/dashboard'
    | '/data'
    | '/install'
    | '/methodology'
    | '/rank'
    | '/methodology/changelog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/dashboard'
    | '/data'
    | '/install'
    | '/methodology'
    | '/rank'
    | '/methodology/changelog'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/dashboard'
    | '/data'
    | '/install'
    | '/methodology'
    | '/rank'
    | '/methodology/changelog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  DataRoute: typeof DataRoute
  InstallRoute: typeof InstallRoute
  MethodologyRoute: typeof MethodologyRouteWithChildren
  RankRoute: typeof RankRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rank': {
      id: '/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof RankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology/changelog': {
      id: '/methodology/changelog'
      path: '/changelog'
      fullPath: '/methodology/changelog'
      preLoaderRoute: typeof MethodologyChangelogRouteImport
      parentRoute: typeof MethodologyRoute
    }
  }
}

interface MethodologyRouteChildren {
  MethodologyChangelogRoute: typeof MethodologyChangelogRoute
}

const MethodologyRouteChildren: MethodologyRouteChildren = {
  MethodologyChangelogRoute: MethodologyChangelogRoute,
}

const MethodologyRouteWithChildren = MethodologyRoute._addFileChildren(
  MethodologyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  DataRoute: DataRoute,
  InstallRoute: InstallRoute,
  MethodologyRoute: MethodologyRouteWithChildren,
  RankRoute: RankRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
